<a href="https://colab.research.google.com/github/shahinaNRI-Degree/PythonMiniProject/blob/main/Introduction_to_numpy_S2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [16]:
# Dot product - m x n || n x p
arr1=np.random.randint(1,2,(1,2))

In [17]:
arr.shape
arr1.shape

(1, 2)

In [19]:
result= np.dot(arr1,arr)

In [21]:
print(result)

[[5 7 9]]


In [10]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[13 17 17]
 [13 12 19]
 [19 16 19]]


In [20]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#r1.I
result=np.dot(r2,r1)

In [26]:
print(result)

[[13. 17. 17.]
 [13. 12. 19.]
 [19. 16. 19.]]


In [28]:
# Mathematical Operations
# + - * /

t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [29]:
print(t1)
print(t2)

[[3 4 4]
 [5 4 3]
 [3 5 4]]
[[3 4 5]
 [3 4 3]
 [3 4 4]]


In [30]:
t3 = t1 + t2
print(t3)

[[6 8 9]
 [8 8 6]
 [6 9 8]]


In [32]:
# Matrix multiplication
result=np.dot(arr1,arr)

In [44]:
# Statistical operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [34]:
print(max)

9


In [36]:
print(median)

8.0


In [38]:
print(std)

1.1653431646335017


In [45]:
print(var)

1.3580246913580245


In [46]:
std * std

1.3580246913580247

In [48]:
# Trigonometric functions

# sin(x)
# cos(x)
# Tan(x) - sin(x) / cos(x)
# cosec - 1 / sin(x)
# sec - 1 / cos(x)
# cot - 1 / tan(x)

angles=np.array([0,15,30,45,60,75,90])

# sin(array)

result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [49]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [50]:
arr=np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr=arr.reshape(2,3)

print(reshapedarr)

[[1 2 3]
 [4 5 6]]


In [51]:
reshapedarr=arr.reshape(3,2)
print(reshapedarr)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
# Convert / flatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[1 2 3 4 5 6]


In [56]:
# Stacking the data

arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

# Vertical Stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

# Horizontal Stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [57]:
# Filtering
arr=np.array([10,20,30,40,50,60,70,80])
farr=arr[arr > 40]
print(farr)

[50 60 70 80]
